[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"

# Removed API redirects - no longer using Netlify functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Removed functions configuration - using Shopify instead 